require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - db/**/*
    - bin/**/*
    - log/**/*
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*
  NewCops: enable

### Rails

Rails:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments

Rails/EnvironmentVariableAccess:
  Enabled: false
  
Rails/I18nLocaleTexts:
  Enabled: false

### Bundler

Bundler/OrderedGems:
  Enabled: false

### Metrics

Metrics/AbcSize:
  Max: 35

Metrics/BlockLength:
  Max: 150

Metrics/MethodLength:
  Max: 30

### Style

Style/AutoResourceCleanup:
  Enabled: true

Style/BlockComments:
  Exclude:
    - "spec/spec_helper.rb"

Style/Encoding:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ImplicitRuntimeError:
  Enabled: true

Style/RegexpLiteral:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: true

Style/StringLiterals:
  Enabled: false

Style/StringMethods:
  Enabled: true

Style/SymbolArray:
  EnforcedStyle: brackets

Style/MixinUsage:
  Enabled: false

Style/StderrPuts:
  Enabled: false

Style/NumericLiteralPrefix:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

### Layout

Layout/LineLength:
  Max: 165

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/FirstMethodParameterLineBreak:
  Enabled: true

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/SpaceAfterComma:
  Enabled: false

Layout/SpaceInsideReferenceBrackets:
  Enabled: false

Layout/SpaceInsideParens:
  Enabled: false

Layout/HashAlignment:
  Enabled: false
