version: '3.4'

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=my-pg-password
    ports:
      - 5432
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3

  app: &app_base
    image: workcation_app
    build:
      context: .
      args:
        - ADDITIONAL_PACKAGES=nodejs yarn
        - EXECJS_RUNTIME=Node
        - FOLDERS_TO_REMOVE=spec node_modules app/assets vendor/assets lib/assets tmp/cache
        - BUNDLE_WITHOUT=development:test
        - RAILS_ENV=production
        - COMMIT_SHA
        - COMMIT_TIME
    environment:
      - APP_HOST=workcation.example.org
      - ROLLBAR_ACCESS_TOKEN=my-rollbar-token
      - DB_HOST=db
      - DB_PASSWORD=my-pg-password
      - DB_USER=postgres
      - RAILS_ENV=production
      - RAILS_MAX_THREADS=5
      - SECRET_KEY_BASE=my-secret-key-base
      - TZ=Europe/Berlin
      - COMMIT_SHA=$COMMIT_SHA
      - COMMIT_TIME=$COMMIT_TIME
    links:
      - db
    ports:
      - 3000
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 3000 || exit 1"]
      interval: 5m
      start_period: 1m
