version: '3.4'

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - db-data:/var/lib/postgresql/data

  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
      - 5900:5900

  app:
    image: workcation_test
    build:
      context: .
      args:
        - ADDITIONAL_PACKAGES=nodejs yarn git
        - EXECJS_RUNTIME=Node
        - RAILS_ENV=test
    environment:
      RAILS_ENV: test
      DB_HOST: db
      POSTGRES_PASSWORD: duubidoo
      SECRET_KEY_BASE: we-dont-need-a-secret-here
      DB_USER: postgres
      DB_PASSWORD: duubidoo
      SELENIUM_REMOTE_HOST: selenium
    ports:
      - 3000
    links:
      - db
      - selenium

volumes:
  db-data:
