name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build the stack
      run: docker-compose -f docker-compose.test.yml build --pull
    - name: Test
      run: docker-compose -f docker-compose.test.yml run --rm app sh -c "./docker/wait-for-services.sh && COVERAGE=true bundle exec rake db:create test"
